language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    recipients:
      - ryrie106@gmail.com

before_install:
  - chmod +x mvnw
  - chmod +x execute-deploy.sh

script: "./mvnw package"

before_deploy:
  - zip -r vidflow *
  - mkdir -p deploy
  - mv vidflow.zip deploy/vidflow.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: vidflow-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ryrie/vidflow
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: vidflow-s3
    key: vidflow.zip
    bundle_type: zip
    application: vidflow
    deployment_group: vidflow-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: ryrie/vidflow
      branch: master