language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw compile"

notifications:
  email:
    recipients:
      - ryrie106@gmail.com

before_install:
  - chmod +x mvnw