spring:
  data:
    rest:
      base-path: /api
  jpa:
    show_sql: true
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mariadb://vidflow-db.c3sgswc5qc63.ap-northeast-2.rds.amazonaws.com:3306/vidflow
    username: mariadmin
    password: mariapassword
    driver-class-name: org.mariadb.jdbc.Driver
