spring:
  jpa:
    show_sql: true
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://vidflow-db.c3sgswc5qc63.ap-northeast-2.rds.amazonaws.com:3306/vidflow
    username: mysqladmin
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: /home/user/uploads

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000


