spring:
  jpa:
    show_sql: true
    database: MYSQL
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/vidflow
    username: mysqluser
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

# server:
#  port: 8080
#  ssl:
#    enabled: true
#    key-store: /home/ubuntu/key/vidflow.jks
#    key-store-password: sslpassword
#    key-password: sslpassword

file:
#  upload-dir: /home/ubuntu/www/uploads
  upload-dir: /home/user/uploads
  upload-chunksize: 1048576 # 1MB

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000


