spring:
  jpa:
    show_sql: true
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://vidflow-db.c3sgswc5qc63.ap-northeast-2.rds.amazonaws.com:3306/vidflow
    username: mariadmin
    password: mariapassword
    driver-class-name: org.mariadb.jdbc.Driver

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000