spring:
  profiles: test
  jpa:
    show_sql: true
    database: h2
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb

app:
  jwtSecret: jwtSecret
  jwtExpirationTime: 3600000 # 1hour
  s3BucketName: foo
  s3UploadURLExpirationTime: 300000 #5mins

---
spring:
  profiles: dev
  jpa:
    show_sql: true
    database: MYSQL
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    # url, username, password : docker-compose에서 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

app:
  # jwtSecret: docker-compose에서 입력
  jwtExpirationTime: 3600000 # 1hour

---
spring:
  profiles: prod
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    # url, username, password: ec2 인스턴스에서 실행 시 argument로 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

app:
  # jwtSecret: ec2 인스턴스에서 실행 시 argument로 입력
  jwtExpirationTime: 3600000 # 1hour
  # s3BucketName: ec2 인스턴스에서 실행 시 argument로 입력
  s3UploadURLExpirationTime: 300000 #5mins