= RestAPI

REST(Representational Style Transfer)은 Web Service의 Architecture Style이다. 처음에 오해할 만한 부분이 REST는 표준이 아니고
스타일이다. 따라서 절대적인 규칙은 없지만, 몇가지 권장하는 원칙이 있으며 그것을 얼마나 잘 적용 하였느냐에 따라
서비스가 `RESTful` 하게 되는 것이다. 마치 몇가지 객체지향 원칙을 가지고 설계 방법에 따라서
해당 프로그램이 객체지향스럽게 되는 것과 같다.

Restful Web Service에서는 모든 리소스가 URI를 가지며 URI로의 어떤 요청을 하면 응답의 Payload가 XML, JSON 등으로 변환되어 반환된다.
그리고 그 응답은 저장된 resource가 재대로 저장/변경 되었는지에 대한 확인이며, 응답에는 다른 리소스로 갈 수 있는 `HyperLink` 를 제공한다.
Web에서는 HTTP 표준 메소드를 사용한다.

무상태(stateless), 표준 프로토콜을 사용하는 Restful System은 속도, 신뢰성, 확장성이 높아지게 된다.

최대한 잘 구성해 보려고 노력했지만, 필요할 때마다 메소드를 작성하다 보니 좀 엉망인것 같다.
Spring Data REST를 사용하면 Object를 Mapping 하는 동시에 HTTP 메소드를
알아서 만들어줘서 그 편이 결과물은 훨씬 좋겠지만 지금은 공부하는 차원에서 직접 설계해 보았고 공부가 많이 되었다.


== 메소드를 설계하면서 고민한 점

- GET에 Body를 넣어도 될까?


== 인증 관련

== 게시물 관련

=== GET /posts/postId

가장 최신의 postId를 돌려준다.

=== GET /posts/{postId}

{postId} 게시물을 보내준다.

=== GET /posts?id={postId}&page={page}

{postId} 이전 게시물의 {post}페이지를 보내준다.

== 댓글 관련

=== GET /comments/{postId}

=== POST /comments/{postId}

