= Spring Security

실제 서비스에서 보안은 매우 중요한 문제이다. Spring Framework에서는 Spring Security라는 프로젝트를 사용하여
보안 설정을 할 수 있다. 조금 복잡하여 처음에 이해하기 쉽지 않지만, 한번 알고 적용하면 높은 수준의 보안을 적용할 수 있다.

== Authentication, Authorization

웹 서비스 보안에서 먼저 알아야 할 두가지 개념이 있다.

Authentication(인증)은 사용자가 서비스를 사용할 수 있는지 허용 여부를 판단 하는 것이며, Authorization(인가)은 인증된 사용자가
어떤 서비스를 사용할 수 있는지 판단 하는 과정이다. Spring Security는 이 두가지 개념을 각각 설정할 수 있게 해 준다.


== 필터 기반 인증

Spring을 사용한 Web Application에서 Security 설정을 하면 `Servlet Filter` 가 추가되고, `DispatcherServlet` 이 웹 요청을 받을
때마다 해당 설정에 맞게 처리한다. 이 프로젝트에는 다음과 같에 설정하였다.

./src/main/java/io/github/ryrie/vidflow/config/SecurityConfiguration.java
[source,java]
include::../src/main/java/io/github/ryrie/vidflow/config/SecurityConfiguration.java[lines=62..93]





== 토큰을 사용한 인증

Restful API Web 서비스에서는 form 기반 로그인을 할 수 없기 때문에 이 프로젝트에서는 로그인시 토큰을 발행하여 브라우저의
localstorage에 저장하고, 모든 요청시 토큰을 포함하도록 했다. 여기서는 JWT(JSON Web Token)을 사용하였다.


=== 로그인을 하면 새로운 token을 반환한다.
./src/main/java/io/github/ryrie/vidflow/controller/UserController.java
[source,java]
include::../src/main/java/io/github/ryrie/vidflow/controller/UserController.java[lines=44..57]


=== 웹 요청시 servlet filter에서 token 정보를 찾는다.
./src/main/java/io/github/ryrie/vidflow/security/JwtAuthenticationFilter.java
[source,java]
include::../src/main/java/io/github/ryrie/vidflow/security/JwtAuthenticationFilter.java[lines=38..63]




== CORS(Cross-Origin Resource Sharing)

CORS란 다른 도메인으로 `Fetch API` 와 같은 `AJAX` 요청시 요청 받는 리소스가 응답 가능한지에 대한 표준 프로토콜이다.
이전에는 이와같은 표준이 없어서 Iframe이나 JSONP 등을 이용하여 `AJAX` 요청을 하였지만 이러한 표준이 생긴 이후 위와 같은 요청은
공격으로 간주된다. CORS는 HTTP Header를 통해 이루어진다.

=== Spring Boot에서 설정

./src/main/java/io/github/ryrie/vidflow/config/WebMvcConfig.java
[source,java]
include::../src/main/java/io/github/ryrie/vidflow/config/WebMvcConfig.java[lines=16..25]




== HTTPS(HTTP Over TLS)

Web Application의 보안은 여러 방법이 있다. 그 중에서도 HTTP의 기반이 되는 TCP 패킷을 암호화하는 TLS를 HTTP의 기반 프로토콜로
사용하면 Application Layer에서는 별다른 보안 설정을 하지 않아도 되기 때문에 간단하고 효과적이다.

최근 웹 서비스에서는 HTTPS가 필수적으로 적용되고 있으며, 보안에 신경을 많이 쓰는 웹 브라우저들은 HTTPS 연결이 아니면
요청을 차단하기도 한다. 따라서 모든 웹 요청에 HTTPS를 적용해야 한다.

Spring boot에서 TLS를 설정하는 방법은 간단하다.

먼저 keytool을 사용하여 TLS 인증서를 jks 파일로 변환한 뒤 ``application.yml``에 다음과 같이 설정하면 된다.

./src/main/resources/application.yml
[source,yaml]
include::../src/main/resources/application.yml[lines=14..20]



